// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice_1;

namespace Practice_1.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20200229090412_CompanyDbContext")]
    partial class CompanyDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Practice_1.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TBC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bank of Georgia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dunder mifflin"
                        });
                });

            modelBuilder.Entity("Practice_1.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Emploies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Email = "gigi10@gmail.com",
                            Name = "Gigi",
                            Phone = "995-75-75-75"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Email = "Lika_lika@gmail.com",
                            Name = "Lika",
                            Phone = "456-35-23-43"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            Email = "Tekla-Tek-Tek@gmail.com",
                            Name = "Tekla",
                            Phone = "123-12-32-44"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            Email = "Pam@gmail.com",
                            Name = "Pam",
                            Phone = "234156454"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 4,
                            Email = "Andrii@gmail.com",
                            Name = "Andrii",
                            Phone = "1234-234-234"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 4,
                            Email = "Sergii@gmail.com",
                            Name = "Sergii",
                            Phone = "123-544-123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
